# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v4
    - name: Instalar node
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - name: Subir artefacto
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./dist
    - name: Despliegue de la app
      uses: actions/deploy-pages@v4.0.5
